<?php

namespace Database\Seeders;

use App\Models\AlumniRecord;
use App\Models\NotificationSetting;
use App\Models\User;
use App\Models\UserPreference;
use Illuminate\Database\Seeder;

class AlumniSeeder extends Seeder
{
    public function run(): void
    {
        // Bangladeshi first & last names pool
        $firstNames = [
            'Rishad', 'Badruddin', 'Monzur', 'Nafiz', 'Golam', 'Mohammad', 'Tanvir',
            'Hasan', 'Kamal', 'Jahangir', 'Farhan', 'Arif', 'Imran', 'Shakib', 'Rafi',
            'Zahid', 'Mamun', 'Sumon', 'Toufiq', 'Ashik', 'Sabbir', 'Jewel', 'Robin',
            'Shafiq', 'Noman', 'Masud', 'Sajjad', 'Rasel', 'Habib', 'Arafat',
            'Faisal', 'Sohel', 'Liton', 'Rubel', 'Milon', 'Shamim', 'Manik', 'Billal',
            'Kamrul', 'Nazmul', 'Rezaul', 'Shahin', 'Kabir', 'Anwar', 'Belal',
            'Delwar', 'Ehsan', 'Firoz', 'Harun', 'Ismail', 'Jamal', 'Latif',
            'Moinul', 'Nasir', 'Omar', 'Pervez', 'Quamrul', 'Rafiq', 'Selim',
            'Tariq', 'Uzzal', 'Wazed', 'Yusuf', 'Zafar', 'Abul', 'Bakar',
            'Chandan', 'Dulal', 'Enamul', 'Farid', 'Giash',
        ];

        $lastNames = [
            'Wahid', 'Ahmed', 'Chowdhury', 'Hasan', 'Rasul', 'Islam', 'Hossain',
            'Murshed', 'Uddin', 'Khan', 'Rahman', 'Alam', 'Bhuiyan', 'Sikder', 'Ali',
            'Mia', 'Sarker', 'Das', 'Mondal', 'Siddique', 'Talukder', 'Biswas',
            'Khandaker', 'Sharif', 'Aziz', 'Kabir', 'Akter', 'Haque', 'Karim',
        ];

        $sections = ['A', 'B', 'C', 'D'];
        $count = 0;

        // Create all 264 alumni records
        foreach ($sections as $section) {
            $maxRoll = $section === 'D' ? 51 : 71;
            for ($roll = 1; $roll <= $maxRoll; $roll++) {
                $fn = $firstNames[$count % count($firstNames)];
                $ln = $lastNames[$count % count($lastNames)];
                $imgIndex = ($count % 50) + 1;

                AlumniRecord::create([
                    'first_name' => $fn,
                    'last_name' => $ln,
                    'section' => $section,
                    'roll_number' => $roll,
                    'profile_image_path' => "alumni_{$imgIndex}.jpg",
                    'is_registered' => false,
                ]);

                $count++;
            }
        }

        // =============================
        // 38 Registered Users with FULL profiles
        // =============================
        $registeredUsers = [
            [
                'section' => 'A', 'roll' => 1,
                'first_name' => 'Rishad', 'last_name' => 'Wahid',
                'email' => 'info@sklentr.com',
                'phone' => '+8801711000001', 'blood_group' => 'A+',
                'occupation' => 'Software Engineer', 'company_name' => 'Sklentr Technologies', 'designation' => 'CEO & Founder',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Banani, Block F, Road 11',
                'bio' => 'Passionate about building digital products that solve real-world problems. Leading Sklentr Technologies since 2015.',
                'facebook_url' => 'https://facebook.com/rishadwahid', 'linkedin_url' => 'https://linkedin.com/in/rishadwahid',
                'whatsapp_number' => '+8801711000001',
                'favorite_teacher' => 'Mr. Abdur Rahim', 'favorite_memory' => 'Annual sports day in 1999 when our section won the relay race.',
                'favorite_hangout' => 'School canteen',
                'emergency_contact_name' => 'Fatema Wahid', 'emergency_contact_phone' => '+8801811000001', 'emergency_contact_relation' => 'Wife',
            ],
            [
                'section' => 'A', 'roll' => 2,
                'first_name' => 'Badruddin', 'last_name' => 'Ahmed',
                'email' => 'badruddin.ahmed@gmail.com',
                'phone' => '+8801711000002', 'blood_group' => 'B+',
                'occupation' => 'Banker', 'company_name' => 'Dutch-Bangla Bank', 'designation' => 'Senior Vice President',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Dhanmondi, Road 27',
                'bio' => 'Banking professional with 20+ years of experience in corporate finance.',
                'facebook_url' => 'https://facebook.com/badruddin.ahmed', 'linkedin_url' => 'https://linkedin.com/in/badruddinahmed',
                'whatsapp_number' => '+8801711000002',
                'favorite_teacher' => 'Mr. Nazrul Islam', 'favorite_memory' => 'Playing cricket during tiffin breaks.',
                'favorite_hangout' => 'Ramna Park after school',
            ],
            [
                'section' => 'A', 'roll' => 3,
                'first_name' => 'Monzur', 'last_name' => 'Chowdhury',
                'email' => 'monzural.murshed@gmail.com',
                'phone' => '+8801714120033', 'blood_group' => 'O+',
                'occupation' => 'Civil Engineer', 'company_name' => 'Rangs Properties Ltd.', 'designation' => 'Project Manager',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Uttara Sector 7, Road 4',
                'bio' => 'Civil engineer specializing in high-rise residential projects in Dhaka.',
                'facebook_url' => 'https://facebook.com/monzur.chowdhury',
                'favorite_teacher' => 'Mrs. Salma Begum', 'favorite_memory' => 'Science fair where we built a solar-powered car model.',
                'favorite_hangout' => 'Shahbagh area',
            ],
            [
                'section' => 'A', 'roll' => 4,
                'first_name' => 'Nafiz', 'last_name' => 'Hasan',
                'email' => 'nafiz.hassan@gmail.com',
                'phone' => '+8801717640259', 'blood_group' => 'B+',
                'occupation' => 'Doctor', 'company_name' => 'Square Hospitals', 'designation' => 'Consultant Cardiologist',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Gulshan-2, Road 105',
                'bio' => 'Cardiologist dedicated to providing accessible heart care to the people of Bangladesh.',
                'facebook_url' => 'https://facebook.com/dr.nafizhasan', 'linkedin_url' => 'https://linkedin.com/in/nafizhasan',
                'whatsapp_number' => '+8801717640259',
                'favorite_teacher' => 'Mr. Shamsul Haque', 'favorite_memory' => 'Winning the inter-school debate competition in 1998.',
                'favorite_hangout' => 'New Market bookshops',
                'emergency_contact_name' => 'Raisa Hasan', 'emergency_contact_phone' => '+8801812345678', 'emergency_contact_relation' => 'Wife',
            ],
            [
                'section' => 'A', 'roll' => 5,
                'first_name' => 'Golam', 'last_name' => 'Rasul',
                'email' => 'syed.golam@gmail.com',
                'phone' => '+8801611000005', 'blood_group' => 'AB+',
                'occupation' => 'Businessman', 'company_name' => 'Rasul Trading Corp.', 'designation' => 'Managing Director',
                'current_city' => 'Chittagong', 'current_country' => 'Bangladesh', 'current_address' => 'Agrabad Commercial Area',
                'bio' => 'Import-export business specializing in raw materials and garment accessories.',
                'facebook_url' => 'https://facebook.com/syedgolamrasul',
                'favorite_teacher' => 'Mr. Harun Rashid', 'favorite_memory' => 'School picnic to Sonargaon.',
                'favorite_hangout' => 'School football ground',
            ],
            [
                'section' => 'A', 'roll' => 6,
                'first_name' => 'Mohammad', 'last_name' => 'Islam',
                'email' => 'mohammad.islam2000@gmail.com',
                'phone' => '+8801911000006', 'blood_group' => 'O-',
                'occupation' => 'IT Consultant', 'company_name' => 'TechnoVista Ltd.', 'designation' => 'Lead Architect',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Mirpur DOHS',
                'bio' => 'Cloud architecture specialist with expertise in AWS and Azure solutions.',
            ],
            [
                'section' => 'A', 'roll' => 7,
                'first_name' => 'Tanvir', 'last_name' => 'Hossain',
                'email' => 'tanvir.hossain@outlook.com',
                'phone' => '+8801511000007', 'blood_group' => 'A-',
                'occupation' => 'Journalist', 'company_name' => 'The Daily Star', 'designation' => 'Senior Reporter',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Motijheel',
                'bio' => 'Investigative journalist covering economic policy and public governance.',
            ],
            [
                'section' => 'A', 'roll' => 10,
                'first_name' => 'Hasan', 'last_name' => 'Murshed',
                'email' => 'hasanmurshed@yahoo.com',
                'phone' => '+8801611000010', 'blood_group' => 'B-',
                'occupation' => 'Pharmacist', 'company_name' => 'Incepta Pharmaceuticals', 'designation' => 'Production Manager',
                'current_city' => 'Savar', 'current_country' => 'Bangladesh', 'current_address' => 'Savar Industrial Area',
                'bio' => 'Pharmaceutical manufacturing specialist with expertise in quality control.',
            ],
            [
                'section' => 'B', 'roll' => 1,
                'first_name' => 'Kamal', 'last_name' => 'Uddin',
                'email' => 'kamal.uddin@gmail.com',
                'phone' => '+8801711000101', 'blood_group' => 'A+',
                'occupation' => 'Architect', 'company_name' => 'Cubeinside Design Studio', 'designation' => 'Principal Architect',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Bashundhara R/A, Block C',
                'bio' => 'Award-winning architect with a passion for sustainable urban design.',
                'favorite_teacher' => 'Mr. Mizanur Rahman',
            ],
            [
                'section' => 'B', 'roll' => 2,
                'first_name' => 'Jahangir', 'last_name' => 'Khan',
                'email' => 'jahangir.khan@hotmail.com',
                'phone' => '+8801611000102', 'blood_group' => 'O+',
                'occupation' => 'Lawyer', 'company_name' => 'Khan & Associates', 'designation' => 'Senior Partner',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Kakrail, Ramna',
                'bio' => 'Corporate lawyer specializing in company law, mergers, and acquisitions.',
            ],
            [
                'section' => 'B', 'roll' => 3,
                'first_name' => 'Farhan', 'last_name' => 'Rahman',
                'email' => 'farhan.rahman@gmail.com',
                'phone' => '+44 7911 123456', 'blood_group' => 'B+',
                'occupation' => 'Data Scientist', 'company_name' => 'Barclays PLC', 'designation' => 'Senior Data Scientist',
                'current_city' => 'London', 'current_country' => 'United Kingdom', 'current_address' => 'Canary Wharf, E14',
                'bio' => 'AI and machine learning specialist in the financial services sector. Living in London since 2008.',
                'linkedin_url' => 'https://linkedin.com/in/farhanrahman',
            ],
            [
                'section' => 'B', 'roll' => 5,
                'first_name' => 'Arif', 'last_name' => 'Alam',
                'email' => 'arif.alam@gmail.com',
                'phone' => '+8801711000105', 'blood_group' => 'AB-',
                'occupation' => 'Professor', 'company_name' => 'University of Dhaka', 'designation' => 'Associate Professor, Physics',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'University Staff Quarter',
                'bio' => 'Academic researcher in quantum physics and optoelectronics.',
            ],
            [
                'section' => 'B', 'roll' => 8,
                'first_name' => 'Imran', 'last_name' => 'Bhuiyan',
                'email' => 'imran.bhuiyan@gmail.com',
                'phone' => '+1 646 555 0108', 'blood_group' => 'A+',
                'occupation' => 'Financial Analyst', 'company_name' => 'Goldman Sachs', 'designation' => 'Vice President',
                'current_city' => 'New York', 'current_country' => 'USA', 'current_address' => 'Manhattan, NY 10004',
                'bio' => 'Wall Street finance professional working in equity derivatives. Proud GLHS alum.',
                'linkedin_url' => 'https://linkedin.com/in/imranbhuiyan',
            ],
            [
                'section' => 'B', 'roll' => 10,
                'first_name' => 'Shakib', 'last_name' => 'Sikder',
                'email' => 'shakib.sikder@gmail.com',
                'phone' => '+8801611000110', 'blood_group' => 'O+',
                'occupation' => 'Restaurant Owner', 'company_name' => 'Spice Garden', 'designation' => 'Owner & Chef',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Banani-11, Road 17',
                'bio' => 'Culinary enthusiast running one of Dhaka\'s most popular Mughlai restaurants.',
            ],
            [
                'section' => 'B', 'roll' => 12,
                'first_name' => 'Rafi', 'last_name' => 'Ali',
                'email' => 'rafi.ali.bd@gmail.com',
                'phone' => '+971 50 123 4567', 'blood_group' => 'B+',
                'occupation' => 'Mechanical Engineer', 'company_name' => 'Emirates Steel', 'designation' => 'Senior Engineer',
                'current_city' => 'Abu Dhabi', 'current_country' => 'UAE', 'current_address' => 'Al Reem Island',
                'bio' => 'Mechanical engineer working in the steel manufacturing industry in the Gulf region.',
            ],
            [
                'section' => 'B', 'roll' => 15,
                'first_name' => 'Zahid', 'last_name' => 'Mia',
                'email' => 'zahid.mia@gmail.com',
                'phone' => '+8801811000115', 'blood_group' => 'A+',
                'occupation' => 'Teacher', 'company_name' => 'Rajuk Uttara Model College', 'designation' => 'Senior Teacher, Mathematics',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Uttara Sector 6',
                'bio' => 'Dedicated educator inspiring the next generation of mathematicians.',
            ],
            [
                'section' => 'C', 'roll' => 1,
                'first_name' => 'Mamun', 'last_name' => 'Sarker',
                'email' => 'mamun.sarker@gmail.com',
                'phone' => '+8801711000201', 'blood_group' => 'O+',
                'occupation' => 'Real Estate Developer', 'company_name' => 'Sheltech Pvt. Ltd.', 'designation' => 'Director',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Gulshan-1, Circle',
                'bio' => 'Real estate developer with a portfolio of 15+ residential and commercial projects.',
            ],
            [
                'section' => 'C', 'roll' => 2,
                'first_name' => 'Sumon', 'last_name' => 'Das',
                'email' => 'sumon.das@gmail.com',
                'phone' => '+8801611000202', 'blood_group' => 'B+',
                'occupation' => 'Graphic Designer', 'company_name' => 'Chaldal.com', 'designation' => 'Head of Design',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Mohakhali DOHS',
                'bio' => 'Creative designer leading the brand and product design team at Bangladesh\'s largest grocery platform.',
            ],
            [
                'section' => 'C', 'roll' => 3,
                'first_name' => 'Toufiq', 'last_name' => 'Mondal',
                'email' => 'toufiq.mondal@gmail.com',
                'phone' => '+61 4 1234 5678', 'blood_group' => 'AB+',
                'occupation' => 'Dentist', 'company_name' => 'Sydney Dental Clinic', 'designation' => 'General Practitioner',
                'current_city' => 'Sydney', 'current_country' => 'Australia', 'current_address' => 'Parramatta, NSW',
                'bio' => 'Dental practitioner providing family dental care in Western Sydney.',
            ],
            [
                'section' => 'C', 'roll' => 5,
                'first_name' => 'Ashik', 'last_name' => 'Siddique',
                'email' => 'ashik.siddique@gmail.com',
                'phone' => '+8801511000205', 'blood_group' => 'A-',
                'occupation' => 'Pilot', 'company_name' => 'Biman Bangladesh Airlines', 'designation' => 'First Officer (Boeing 787)',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Airport Road, Kurmitola',
                'bio' => 'Commercial pilot living the childhood dream of flying. Over 5,000 flight hours logged.',
            ],
            [
                'section' => 'C', 'roll' => 7,
                'first_name' => 'Sabbir', 'last_name' => 'Talukder',
                'email' => 'sabbir.talukder@gmail.com',
                'phone' => '+8801611000207', 'blood_group' => 'O-',
                'occupation' => 'Chartered Accountant', 'company_name' => 'KPMG Bangladesh', 'designation' => 'Manager, Audit & Assurance',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Baridhara, Block J',
                'bio' => 'Chartered accountant providing audit and advisory services to multinationals.',
            ],
            [
                'section' => 'C', 'roll' => 10,
                'first_name' => 'Jewel', 'last_name' => 'Biswas',
                'email' => 'jewel.biswas@gmail.com',
                'phone' => '+8801711000210', 'blood_group' => 'B+',
                'occupation' => 'Photographer', 'company_name' => 'Jewel Captures', 'designation' => 'Freelance Photographer',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Old Dhaka, Shakhari Bazar',
                'bio' => 'Documentary and wedding photographer capturing the soul of Bangladesh.',
            ],
            [
                'section' => 'C', 'roll' => 12,
                'first_name' => 'Robin', 'last_name' => 'Khandaker',
                'email' => 'robin.khandaker@gmail.com',
                'phone' => '+1 416 555 0112', 'blood_group' => 'A+',
                'occupation' => 'Software Developer', 'company_name' => 'Shopify', 'designation' => 'Staff Engineer',
                'current_city' => 'Toronto', 'current_country' => 'Canada', 'current_address' => 'Downtown Toronto, ON',
                'bio' => 'Full-stack developer at Shopify building e-commerce solutions at scale.',
                'linkedin_url' => 'https://linkedin.com/in/robinkhandaker',
            ],
            [
                'section' => 'C', 'roll' => 15,
                'first_name' => 'Shafiq', 'last_name' => 'Sharif',
                'email' => 'shafiq.sharif@gmail.com',
                'phone' => '+8801911000215', 'blood_group' => 'O+',
                'occupation' => 'Government Officer', 'company_name' => 'Ministry of Finance', 'designation' => 'Joint Secretary',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Segunbagicha, Dhaka-1000',
                'bio' => 'Public servant working in economic policy and fiscal management.',
            ],
            [
                'section' => 'C', 'roll' => 20,
                'first_name' => 'Noman', 'last_name' => 'Aziz',
                'email' => 'noman.aziz@gmail.com',
                'phone' => '+966 50 123 4567', 'blood_group' => 'B-',
                'occupation' => 'Petroleum Engineer', 'company_name' => 'Saudi Aramco', 'designation' => 'Senior Engineer',
                'current_city' => 'Dhahran', 'current_country' => 'Saudi Arabia', 'current_address' => 'Aramco Residential Camp',
                'bio' => 'Petroleum engineer working in upstream oil exploration and production.',
            ],
            [
                'section' => 'D', 'roll' => 1,
                'first_name' => 'Masud', 'last_name' => 'Kabir',
                'email' => 'masud.kabir@gmail.com',
                'phone' => '+8801711000301', 'blood_group' => 'A+',
                'occupation' => 'Garments Exporter', 'company_name' => 'Kabir Garments Ltd.', 'designation' => 'Managing Director',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Tejgaon Industrial Area',
                'bio' => 'RMG exporter supplying premium knitwear to European and American brands.',
            ],
            [
                'section' => 'D', 'roll' => 2,
                'first_name' => 'Sajjad', 'last_name' => 'Akter',
                'email' => 'sajjad.akter@gmail.com',
                'phone' => '+8801611000302', 'blood_group' => 'B+',
                'occupation' => 'Navy Officer', 'company_name' => 'Bangladesh Navy', 'designation' => 'Lieutenant Commander',
                'current_city' => 'Chittagong', 'current_country' => 'Bangladesh', 'current_address' => 'BNS Issa Khan',
                'bio' => 'Serving the nation in the Bangladesh Navy with pride and honor.',
            ],
            [
                'section' => 'D', 'roll' => 3,
                'first_name' => 'Rasel', 'last_name' => 'Haque',
                'email' => 'rasel.haque@gmail.com',
                'phone' => '+8801511000303', 'blood_group' => 'O+',
                'occupation' => 'Neurologist', 'company_name' => 'National Institute of Neurosciences', 'designation' => 'Associate Professor',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Sher-e-Bangla Nagar',
                'bio' => 'Neurologist and researcher specializing in stroke prevention and treatment.',
            ],
            [
                'section' => 'D', 'roll' => 5,
                'first_name' => 'Habib', 'last_name' => 'Karim',
                'email' => 'habib.karim@gmail.com',
                'phone' => '+8801711000305', 'blood_group' => 'AB+',
                'occupation' => 'Marketing Director', 'company_name' => 'Grameenphone', 'designation' => 'Director of Digital Marketing',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Gulshan Circle-2',
                'bio' => 'Digital marketing leader driving customer acquisition for Bangladesh\'s largest telecom.',
            ],
            [
                'section' => 'D', 'roll' => 8,
                'first_name' => 'Arafat', 'last_name' => 'Wahid',
                'email' => 'arafat.wahid@gmail.com',
                'phone' => '+49 176 1234 5678', 'blood_group' => 'A+',
                'occupation' => 'Research Scientist', 'company_name' => 'Max Planck Institute', 'designation' => 'Postdoctoral Researcher',
                'current_city' => 'Munich', 'current_country' => 'Germany', 'current_address' => 'Garching bei München',
                'bio' => 'Materials science researcher working on next-generation semiconductor materials.',
                'linkedin_url' => 'https://linkedin.com/in/arafatwahid',
            ],
            [
                'section' => 'D', 'roll' => 10,
                'first_name' => 'Faisal', 'last_name' => 'Ahmed',
                'email' => 'faisal.ahmed@gmail.com',
                'phone' => '+8801911000310', 'blood_group' => 'B+',
                'occupation' => 'Entrepreneur', 'company_name' => 'FoodPanda BD (ex)', 'designation' => 'Co-Founder (Exited)',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Baridhara DOHS',
                'bio' => 'Serial entrepreneur in the tech and food-tech space. Angel investor.',
            ],
            [
                'section' => 'D', 'roll' => 12,
                'first_name' => 'Sohel', 'last_name' => 'Islam',
                'email' => 'sohel.islam@gmail.com',
                'phone' => '+8801611000312', 'blood_group' => 'O+',
                'occupation' => 'Army Officer', 'company_name' => 'Bangladesh Army', 'designation' => 'Major',
                'current_city' => 'Bogra', 'current_country' => 'Bangladesh', 'current_address' => 'Bogra Cantonment',
                'bio' => 'Proudly serving in the Bangladesh Army. Discipline, duty, dedication.',
            ],
            [
                'section' => 'D', 'roll' => 15,
                'first_name' => 'Liton', 'last_name' => 'Hossain',
                'email' => 'liton.hossain@gmail.com',
                'phone' => '+60 12 345 6789', 'blood_group' => 'AB-',
                'occupation' => 'Hotel Manager', 'company_name' => 'Shangri-La Hotel', 'designation' => 'Assistant General Manager',
                'current_city' => 'Kuala Lumpur', 'current_country' => 'Malaysia', 'current_address' => 'Jalan Sultan Ismail',
                'bio' => 'Hospitality professional managing 5-star hotel operations in Southeast Asia.',
            ],
            [
                'section' => 'D', 'roll' => 18,
                'first_name' => 'Rubel', 'last_name' => 'Khan',
                'email' => 'rubel.khan@gmail.com',
                'phone' => '+8801711000318', 'blood_group' => 'B+',
                'occupation' => 'Film Director', 'company_name' => 'RK Productions', 'designation' => 'Director',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'FDC, Tejgaon',
                'bio' => 'Independent filmmaker creating meaningful Bengali cinema.',
            ],
            [
                'section' => 'D', 'roll' => 20,
                'first_name' => 'Milon', 'last_name' => 'Rahman',
                'email' => 'milon.rahman@gmail.com',
                'phone' => '+8801611000320', 'blood_group' => 'O+',
                'occupation' => 'Police Officer', 'company_name' => 'Bangladesh Police', 'designation' => 'Additional Superintendent',
                'current_city' => 'Sylhet', 'current_country' => 'Bangladesh', 'current_address' => 'Police Lines, Sylhet',
                'bio' => 'Law enforcement officer serving the people with integrity.',
            ],
            [
                'section' => 'A', 'roll' => 15,
                'first_name' => 'Shamim', 'last_name' => 'Hossain',
                'email' => 'shamim.hossain@gmail.com',
                'phone' => '+8801911000015', 'blood_group' => 'A+',
                'occupation' => 'Telecom Engineer', 'company_name' => 'Robi Axiata', 'designation' => 'Network Optimization Lead',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Gulshan-1',
                'bio' => 'Telecom engineer optimizing 4G/5G network coverage across Bangladesh.',
            ],
            [
                'section' => 'A', 'roll' => 20,
                'first_name' => 'Manik', 'last_name' => 'Uddin',
                'email' => 'manik.uddin@gmail.com',
                'phone' => '+8801511000020', 'blood_group' => 'B-',
                'occupation' => 'Ship Captain', 'company_name' => 'Bangladesh Shipping Corporation', 'designation' => 'Captain',
                'current_city' => 'Chittagong', 'current_country' => 'Bangladesh', 'current_address' => 'Port Area, Chittagong',
                'bio' => 'Merchant marine captain navigating international waters for over 15 years.',
            ],
            // ── 12 additional members (39–50) ──
            [
                'section' => 'A', 'roll' => 25,
                'first_name' => 'Billal', 'last_name' => 'Hossain',
                'email' => 'billal.hossain@gmail.com',
                'phone' => '+8801711000025', 'blood_group' => 'A+',
                'occupation' => 'Pharmacist', 'company_name' => 'Beximco Pharma', 'designation' => 'Quality Assurance Manager',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Tongi Industrial Area',
                'bio' => 'QA specialist ensuring world-class pharmaceutical standards at one of Bangladesh\'s leading pharma companies.',
            ],
            [
                'section' => 'A', 'roll' => 30,
                'first_name' => 'Kamrul', 'last_name' => 'Islam',
                'email' => 'kamrul.islam@gmail.com',
                'phone' => '+8801611000030', 'blood_group' => 'O+',
                'occupation' => 'Customs Officer', 'company_name' => 'Bangladesh Customs', 'designation' => 'Deputy Commissioner',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Kawran Bazar',
                'bio' => 'Public servant managing customs operations to facilitate international trade.',
            ],
            [
                'section' => 'A', 'roll' => 35,
                'first_name' => 'Nazmul', 'last_name' => 'Haque',
                'email' => 'nazmul.haque@gmail.com',
                'phone' => '+8801811000035', 'blood_group' => 'B+',
                'occupation' => 'School Principal', 'company_name' => 'Ideal School & College', 'designation' => 'Vice Principal',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Motijheel, Dhaka-1000',
                'bio' => 'Educator with 20 years of experience shaping young minds at one of Dhaka\'s premier schools.',
            ],
            [
                'section' => 'B', 'roll' => 20,
                'first_name' => 'Rezaul', 'last_name' => 'Karim',
                'email' => 'rezaul.karim@gmail.com',
                'phone' => '+8801911000120', 'blood_group' => 'AB+',
                'occupation' => 'Textile Engineer', 'company_name' => 'Ha-Meem Group', 'designation' => 'Production Director',
                'current_city' => 'Gazipur', 'current_country' => 'Bangladesh', 'current_address' => 'Gazipur BSCIC',
                'bio' => 'Textile engineering professional overseeing large-scale garment production for international brands.',
            ],
            [
                'section' => 'B', 'roll' => 25,
                'first_name' => 'Shahin', 'last_name' => 'Alam',
                'email' => 'shahin.alam@gmail.com',
                'phone' => '+8801511000125', 'blood_group' => 'A-',
                'occupation' => 'Agriculturist', 'company_name' => 'ACI Agribusiness', 'designation' => 'Regional Manager',
                'current_city' => 'Bogra', 'current_country' => 'Bangladesh', 'current_address' => 'Sherpur Road, Bogra',
                'bio' => 'Agricultural professional promoting modern farming techniques across Northern Bangladesh.',
            ],
            [
                'section' => 'B', 'roll' => 30,
                'first_name' => 'Kabir', 'last_name' => 'Uddin',
                'email' => 'kabir.uddin@gmail.com',
                'phone' => '+8801711000130', 'blood_group' => 'O-',
                'occupation' => 'Civil Surgeon', 'company_name' => 'Dhaka Civil Surgeon Office', 'designation' => 'Civil Surgeon',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Fulbaria, Dhaka',
                'bio' => 'Government health official managing public healthcare delivery for Dhaka district.',
            ],
            [
                'section' => 'C', 'roll' => 25,
                'first_name' => 'Anwar', 'last_name' => 'Hossain',
                'email' => 'anwar.hossain@gmail.com',
                'phone' => '+8801611000225', 'blood_group' => 'B-',
                'occupation' => 'Marine Engineer', 'company_name' => 'Maersk Line', 'designation' => 'Chief Engineer',
                'current_city' => 'Singapore', 'current_country' => 'Singapore', 'current_address' => 'Tanjong Pagar',
                'bio' => 'Marine engineer ensuring safe vessel operations on international shipping routes across Asia-Pacific.',
            ],
            [
                'section' => 'C', 'roll' => 30,
                'first_name' => 'Belal', 'last_name' => 'Ahmed',
                'email' => 'belal.ahmed@gmail.com',
                'phone' => '+8801711000230', 'blood_group' => 'A+',
                'occupation' => 'Journalist', 'company_name' => 'Prothom Alo', 'designation' => 'Senior Staff Reporter',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Karwan Bazar, Dhaka',
                'bio' => 'Award-winning journalist covering national politics and social issues for Bangladesh\'s largest daily newspaper.',
            ],
            [
                'section' => 'C', 'roll' => 35,
                'first_name' => 'Delwar', 'last_name' => 'Sikder',
                'email' => 'delwar.sikder@gmail.com',
                'phone' => '+8801811000235', 'blood_group' => 'O+',
                'occupation' => 'Electrical Engineer', 'company_name' => 'Bangladesh Power Development Board', 'designation' => 'Executive Engineer',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Agargaon, Dhaka',
                'bio' => 'Power sector engineer working on national grid expansion and renewable energy projects.',
            ],
            [
                'section' => 'D', 'roll' => 25,
                'first_name' => 'Ehsan', 'last_name' => 'Mia',
                'email' => 'ehsan.mia@gmail.com',
                'phone' => '+971 55 987 6543', 'blood_group' => 'B+',
                'occupation' => 'Construction Manager', 'company_name' => 'Emaar Properties', 'designation' => 'Project Manager',
                'current_city' => 'Dubai', 'current_country' => 'UAE', 'current_address' => 'Dubai Marina',
                'bio' => 'Construction management professional working on luxury real estate projects in the Gulf region.',
            ],
            [
                'section' => 'D', 'roll' => 30,
                'first_name' => 'Firoz', 'last_name' => 'Sarker',
                'email' => 'firoz.sarker@gmail.com',
                'phone' => '+8801911000330', 'blood_group' => 'AB-',
                'occupation' => 'Veterinarian', 'company_name' => 'Dhaka Zoo', 'designation' => 'Senior Veterinary Surgeon',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Mirpur-1, Dhaka',
                'bio' => 'Veterinary professional dedicated to wildlife conservation and animal welfare.',
            ],
            [
                'section' => 'D', 'roll' => 35,
                'first_name' => 'Harun', 'last_name' => 'Das',
                'email' => 'harun.das@gmail.com',
                'phone' => '+8801611000335', 'blood_group' => 'O+',
                'occupation' => 'Railway Engineer', 'company_name' => 'Bangladesh Railway', 'designation' => 'Assistant Director',
                'current_city' => 'Dhaka', 'current_country' => 'Bangladesh', 'current_address' => 'Kamalapur, Dhaka',
                'bio' => 'Railway infrastructure engineer working on the Dhaka Metro Rail and national rail modernization projects.',
            ],
            [
                'section' => 'D', 'roll' => 40,
                'first_name' => 'Ismail', 'last_name' => 'Mondal',
                'email' => 'ismail.mondal@gmail.com',
                'phone' => '+8801711000340', 'blood_group' => 'A-',
                'occupation' => 'Pharmacist', 'company_name' => 'Square Pharmaceuticals', 'designation' => 'Supply Chain Manager',
                'current_city' => 'Pabna', 'current_country' => 'Bangladesh', 'current_address' => 'Square Industrial Park, Pabna',
                'bio' => 'Pharmaceutical supply chain specialist ensuring timely medicine distribution across Bangladesh.',
            ],
        ];

        foreach ($registeredUsers as $i => $data) {
            $record = AlumniRecord::where('section', $data['section'])
                ->where('roll_number', $data['roll'])
                ->first();

            if (!$record) continue;

            // Assign a unique, dedicated image (alumni_1..50) to each registered user
            $record->update([
                'first_name' => $data['first_name'],
                'last_name' => $data['last_name'],
                'profile_image_path' => 'alumni_' . ($i + 1) . '.jpg',
                'is_registered' => true,
            ]);

            $user = User::create([
                'alumni_record_id' => $record->id,
                'email' => $data['email'],
                'phone' => $data['phone'],
                'password' => 'password123',
                'is_active' => true,
                'blood_group' => $data['blood_group'] ?? null,
                'occupation' => $data['occupation'] ?? null,
                'company_name' => $data['company_name'] ?? null,
                'designation' => $data['designation'] ?? null,
                'current_city' => $data['current_city'] ?? null,
                'current_country' => $data['current_country'] ?? null,
                'current_address' => $data['current_address'] ?? null,
                'bio' => $data['bio'] ?? null,
                'facebook_url' => $data['facebook_url'] ?? null,
                'linkedin_url' => $data['linkedin_url'] ?? null,
                'whatsapp_number' => $data['whatsapp_number'] ?? null,
                'favorite_teacher' => $data['favorite_teacher'] ?? null,
                'favorite_memory' => $data['favorite_memory'] ?? null,
                'favorite_hangout' => $data['favorite_hangout'] ?? null,
                'emergency_contact_name' => $data['emergency_contact_name'] ?? null,
                'emergency_contact_phone' => $data['emergency_contact_phone'] ?? null,
                'emergency_contact_relation' => $data['emergency_contact_relation'] ?? null,
            ]);

            NotificationSetting::create(['user_id' => $user->id]);
            UserPreference::create(['user_id' => $user->id, 'theme' => 'light']);
        }
    }
}
